on: [push]


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello World Action steps
      id: hello
      uses: carnells/my-javascript-action
      with:
        who-to-greet: 'Carnell the OctoBot'
    # Use the output from the 'hello' steps
    - name: Get the output time
      run: echo "time was ${{ steps.steps.hello.outputs.time }}"
